weblog_agent.sources  = weblog_source
weblog_agent.sinks    = file_sink
weblog_agent.channels = mem_channel

weblog_agent.sources.weblog_source.type      = exec
weblog_agent.sources.weblog_source.command   = tail -F /tmp/testlogs/access.log
weblog_agent.sources.weblog_source.channels  = mem_channel
weblog_agent.sources.weblog_source.batchSize = 10

weblog_agent.channels.mem_channel.type                = memory
weblog_agent.channels.mem_channel.capacity            = 1000
weblog_agent.channels.mem_channel.transactionCapacity = 100

weblog_agent.sinks.file_sink.type              = file_roll
weblog_agent.sinks.file_sink.channel           = mem_channel
weblog_agent.sinks.file_sink.sink.directory    = /tmp/flume_output
weblog_agent.sinks.file_sink.sink.rollInterval = 30
